name: SAST CI
on:
  push: 
    branches: main 
  
permissions:
  contents: read
  security-events: write
  issues: write

jobs:
  sast:
    name: SAST checkout
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Code Checkout 
        uses: actions/checkout@v3

      - name: 📥 Adicionar repositório do Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
        
      - name: 📥 Install docker
        run: |
          sudo apt-get install -y docker-ce=5:20.10.13~3-0~ubuntu-focal \
                                  docker-ce-cli=5:20.10.13~3-0~ubuntu-focal \
                                  containerd.io --allow-downgrades
          sudo apt-mark hold docker-ce docker-ce-cli containerd.io
          
      - name: 🏗️ Verify docker version
        run: docker --version

      - name: Horusec
        run: |
          mkdir reports
          docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src/horusec horuszup/horusec-cli:latest horusec start -p /src/horusec -P $(pwd) -o='sarif' -O=/src/horusec/reports/horusec_report.sarif
      
      - name: Archive horusec report
        uses: actions/upload-artifact@v4
        with:
          name: horusec_report
          path: reports/horusec_report.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/horusec_report.sarif
          category: sast-report

      

      
